String baseUrl = "${AppUrl.host}/storage/app/";

class AppUrl {
  //TODO: Change Url before Deploying

  // static const String host = 'https://staging.creatoo.co.in';
  // static const String host = 'http://192.168.0.36:8000';
  // static const String host = 'https://portal.creatoo.co.in';
  static const String host = 'https://api.tapbill.in/api';
  static const String baseUrl = '$host/api';
  static const String razorpayOrderId = 'https://api.razorpay.com/v1/orders';

  static const String creatorLogin = '$baseUrl/auth/creatorLogin';
  static const String resendCreatorOtp = '$baseUrl/auth/resendCreatorOtp';
  static const String businessLogin = '$baseUrl/auth/businessLogin';
  static const String resendBusinessOtp = '$baseUrl/auth/resendBusinessOtp';
  static const String registerBusiness = '$baseUrl/auth/businessRegister';
  static const String registerCreator = '$baseUrl/auth/creatorRegister';
  static const String fetchInstaUser = '$baseUrl/fetchInstaUser';
  static const String homeData = '$baseUrl/api/home/getHomeData';
  static const String searchUser = '$baseUrl/api/users/search';
  static const String searchBusinessAndCreator = '$baseUrl/api/users/searchBusinessAndCreator';
  static const String inactiveUser = '$baseUrl/api/users/inactiveUser';
  static const String logout = '$baseUrl/api/auth/logout';
  static const String viewMyPost = '$baseUrl/api/post/myPost';
  static const String viewProfile = '$baseUrl/api/auth/viewProfile';
  static const String editBusinessProfile = '$baseUrl/api/auth/editBusinessProfile';
  static const String editCreatorProfile = '$baseUrl/api/auth/editCreatorProfile';
  static const String instaVerificationApi = '$baseUrl/submitInstaVerification';
  static const String getBusinessTypes = '$baseUrl/api/businessType/getBusinessTypes';
  static const String businessWalletTransaction = '$baseUrl/api/walletTransaction/businessWalletTransaction';
  static const String addPost = '$baseUrl/api/post/add';
  static const String postPaymentStatus = '$baseUrl/api/post/postPaymentStatus';
  static const String getPostApplicationList = '$baseUrl/api/post/getPostApplicationList';
  static const String addCreatorToCart = '$baseUrl/api/cart/addCart';
  static const String shortlistCreator = '$baseUrl/api/cart/addShortlist';
  static const String settingApi = '$baseUrl/api/setting/setting';
  static const String releasePaymentToCreatorApi = '$baseUrl/api/payment/paymentReleaseToCreator';
  static const String creatorHomeApi = '$baseUrl/api/home/getCreatorHome';
  static const String getPostOpportunitiesApi = '$baseUrl/api/opportunity/getAllOpportunities';
  static const String postReportRequestApi = '$baseUrl/api/post/postReportRequest';
  static const String postInterestApi = '$baseUrl/api/post/postInterest';
  static const String opportunityDetailsApi = '$baseUrl/api/opportunity/getOpportunityDetails';
  static const String creatorWalletTransaction = '$baseUrl/api/walletTransaction/creatorWalletTransaction';
  static const String creatorWithdrawRequestApi = '$baseUrl/api/withdrawRequest/add';
  static const String addBusinessWalletTransactionApi = '$baseUrl/api/walletTransaction/addBusinessWalletTransaction';
  static const String getBusinessListApi = '$baseUrl/api/business/getBusinessList';
  static const String creatooRequestApi = '$baseUrl/creatooRequest';
  static const String paymentDetailsApi = '$baseUrl/api/payment/paymentDetails';
  static const String getPaymentDetailApi = '$baseUrl/api/payment/getPaymentDetail';
  static const String creatorContactApi = '$baseUrl/api/home/getCreatorContact';
  static const String creatooPointsTransactionApi = '$baseUrl/api/points/creatooPointsTransaction';
  static const String validatePointsApi = '$baseUrl/api/points/validateCreatooPoints';
  static const String transferPointsApi = '$baseUrl/api/points/transferCreatooPoints';
  static const String businessPointsTransaction = '$baseUrl/api/points/businessPointsTransaction';
  static const String businessSetting = '$baseUrl/api/setting/businessSetting';
  static const String getBusinessSetting = '$baseUrl/api/setting/getBusinessSetting';
  static const String editBusinessDiscount = '$baseUrl/api/business/setDiscount';
  static const String editBusinessDescription = '$baseUrl/api/business/businessDescription';
  static const String sendFeedback = '$baseUrl/api/review/reviewSubmit';
  static const String skipFeedback = '$baseUrl/api/review/skipReview';
  static const String getNotificationApi = '$baseUrl/NewNotificationList';
  static const String createOrderApi = '$baseUrl/createOrder';
  static const String applyOffers = '$baseUrl/applyOffers';
  static const String paymentStatus = '$baseUrl/api/payment/paymentSuccess';
  static const String reviewList = '$baseUrl/api/review/ListOfAllReview';
  static const String processPayment = '$baseUrl/api/payment/processPayment';
  static const String checkTransactionStatus = '$baseUrl/api/walletTransaction/checkTransactionStatus';
}
